// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type newsCategoryTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *newsCategoryTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("news_categories").
func (v *newsCategoryTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *newsCategoryTableType) Columns() []string {
	return []string{
		"news_id",
		"category_id",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *newsCategoryTableType) NewStruct() reform.Struct {
	return new(NewsCategory)
}

// NewRecord makes a new record for that table.
func (v *newsCategoryTableType) NewRecord() reform.Record {
	return new(NewsCategory)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *newsCategoryTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// NewsCategoryTable represents news_categories view or table in SQL database.
var NewsCategoryTable = &newsCategoryTableType{
	s: parse.StructInfo{
		Type:    "NewsCategory",
		SQLName: "news_categories",
		Fields: []parse.FieldInfo{
			{Name: "NewsId", Type: "int64", Column: "news_id"},
			{Name: "CategoryId", Type: "int64", Column: "category_id"},
		},
		PKFieldIndex: 0,
	},
	z: new(NewsCategory).Values(),
}

// String returns a string representation of this struct or record.
func (s NewsCategory) String() string {
	res := make([]string, 2)
	res[0] = "NewsId: " + reform.Inspect(s.NewsId, true)
	res[1] = "CategoryId: " + reform.Inspect(s.CategoryId, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *NewsCategory) Values() []interface{} {
	return []interface{}{
		s.NewsId,
		s.CategoryId,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *NewsCategory) Pointers() []interface{} {
	return []interface{}{
		&s.NewsId,
		&s.CategoryId,
	}
}

// View returns View object for that struct.
func (s *NewsCategory) View() reform.View {
	return NewsCategoryTable
}

// Table returns Table object for that record.
func (s *NewsCategory) Table() reform.Table {
	return NewsCategoryTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *NewsCategory) PKValue() interface{} {
	return s.NewsId
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *NewsCategory) PKPointer() interface{} {
	return &s.NewsId
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *NewsCategory) HasPK() bool {
	return s.NewsId != NewsCategoryTable.z[NewsCategoryTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.NewsId = pk.
func (s *NewsCategory) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = NewsCategoryTable
	_ reform.Struct = (*NewsCategory)(nil)
	_ reform.Table  = NewsCategoryTable
	_ reform.Record = (*NewsCategory)(nil)
	_ fmt.Stringer  = (*NewsCategory)(nil)
)

func init() {
	parse.AssertUpToDate(&NewsCategoryTable.s, new(NewsCategory))
}
