// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// INewsRepository is an autogenerated mock type for the INewsRepository type
type INewsRepository struct {
	mock.Mock
}

type INewsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *INewsRepository) EXPECT() *INewsRepository_Expecter {
	return &INewsRepository_Expecter{mock: &_m.Mock}
}

// CreateNews provides a mock function with given fields: createForm
func (_m *INewsRepository) CreateNews(createForm models.NewsCreateForm) (int64, error) {
	ret := _m.Called(createForm)

	if len(ret) == 0 {
		panic("no return value specified for CreateNews")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(models.NewsCreateForm) (int64, error)); ok {
		return rf(createForm)
	}
	if rf, ok := ret.Get(0).(func(models.NewsCreateForm) int64); ok {
		r0 = rf(createForm)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(models.NewsCreateForm) error); ok {
		r1 = rf(createForm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// INewsRepository_CreateNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNews'
type INewsRepository_CreateNews_Call struct {
	*mock.Call
}

// CreateNews is a helper method to define mock.On call
//   - createForm models.NewsCreateForm
func (_e *INewsRepository_Expecter) CreateNews(createForm interface{}) *INewsRepository_CreateNews_Call {
	return &INewsRepository_CreateNews_Call{Call: _e.mock.On("CreateNews", createForm)}
}

func (_c *INewsRepository_CreateNews_Call) Run(run func(createForm models.NewsCreateForm)) *INewsRepository_CreateNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.NewsCreateForm))
	})
	return _c
}

func (_c *INewsRepository_CreateNews_Call) Return(_a0 int64, _a1 error) *INewsRepository_CreateNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *INewsRepository_CreateNews_Call) RunAndReturn(run func(models.NewsCreateForm) (int64, error)) *INewsRepository_CreateNews_Call {
	_c.Call.Return(run)
	return _c
}

// GetNews provides a mock function with given fields: limit, offset
func (_m *INewsRepository) GetNews(limit int64, offset int64) ([]models.NewsWithCategories, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetNews")
	}

	var r0 []models.NewsWithCategories
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64) ([]models.NewsWithCategories, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) []models.NewsWithCategories); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.NewsWithCategories)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// INewsRepository_GetNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNews'
type INewsRepository_GetNews_Call struct {
	*mock.Call
}

// GetNews is a helper method to define mock.On call
//   - limit int64
//   - offset int64
func (_e *INewsRepository_Expecter) GetNews(limit interface{}, offset interface{}) *INewsRepository_GetNews_Call {
	return &INewsRepository_GetNews_Call{Call: _e.mock.On("GetNews", limit, offset)}
}

func (_c *INewsRepository_GetNews_Call) Run(run func(limit int64, offset int64)) *INewsRepository_GetNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *INewsRepository_GetNews_Call) Return(_a0 []models.NewsWithCategories, _a1 error) *INewsRepository_GetNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *INewsRepository_GetNews_Call) RunAndReturn(run func(int64, int64) ([]models.NewsWithCategories, error)) *INewsRepository_GetNews_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNews provides a mock function with given fields: newsId, updateFields, categories
func (_m *INewsRepository) UpdateNews(newsId int64, updateFields map[string]interface{}, categories *[]int64) error {
	ret := _m.Called(newsId, updateFields, categories)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, map[string]interface{}, *[]int64) error); ok {
		r0 = rf(newsId, updateFields, categories)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// INewsRepository_UpdateNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNews'
type INewsRepository_UpdateNews_Call struct {
	*mock.Call
}

// UpdateNews is a helper method to define mock.On call
//   - newsId int64
//   - updateFields map[string]interface{}
//   - categories *[]int64
func (_e *INewsRepository_Expecter) UpdateNews(newsId interface{}, updateFields interface{}, categories interface{}) *INewsRepository_UpdateNews_Call {
	return &INewsRepository_UpdateNews_Call{Call: _e.mock.On("UpdateNews", newsId, updateFields, categories)}
}

func (_c *INewsRepository_UpdateNews_Call) Run(run func(newsId int64, updateFields map[string]interface{}, categories *[]int64)) *INewsRepository_UpdateNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(map[string]interface{}), args[2].(*[]int64))
	})
	return _c
}

func (_c *INewsRepository_UpdateNews_Call) Return(_a0 error) *INewsRepository_UpdateNews_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *INewsRepository_UpdateNews_Call) RunAndReturn(run func(int64, map[string]interface{}, *[]int64) error) *INewsRepository_UpdateNews_Call {
	_c.Call.Return(run)
	return _c
}

// NewINewsRepository creates a new instance of INewsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINewsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *INewsRepository {
	mock := &INewsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
