// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "service/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// INewsService is an autogenerated mock type for the INewsService type
type INewsService struct {
	mock.Mock
}

type INewsService_Expecter struct {
	mock *mock.Mock
}

func (_m *INewsService) EXPECT() *INewsService_Expecter {
	return &INewsService_Expecter{mock: &_m.Mock}
}

// CreateNews provides a mock function with given fields: createForm
func (_m *INewsService) CreateNews(createForm models.NewsCreateForm) (int64, error) {
	ret := _m.Called(createForm)

	if len(ret) == 0 {
		panic("no return value specified for CreateNews")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(models.NewsCreateForm) (int64, error)); ok {
		return rf(createForm)
	}
	if rf, ok := ret.Get(0).(func(models.NewsCreateForm) int64); ok {
		r0 = rf(createForm)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(models.NewsCreateForm) error); ok {
		r1 = rf(createForm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// INewsService_CreateNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNews'
type INewsService_CreateNews_Call struct {
	*mock.Call
}

// CreateNews is a helper method to define mock.On call
//   - createForm models.NewsCreateForm
func (_e *INewsService_Expecter) CreateNews(createForm interface{}) *INewsService_CreateNews_Call {
	return &INewsService_CreateNews_Call{Call: _e.mock.On("CreateNews", createForm)}
}

func (_c *INewsService_CreateNews_Call) Run(run func(createForm models.NewsCreateForm)) *INewsService_CreateNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.NewsCreateForm))
	})
	return _c
}

func (_c *INewsService_CreateNews_Call) Return(_a0 int64, _a1 error) *INewsService_CreateNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *INewsService_CreateNews_Call) RunAndReturn(run func(models.NewsCreateForm) (int64, error)) *INewsService_CreateNews_Call {
	_c.Call.Return(run)
	return _c
}

// EditNews provides a mock function with given fields: newsId, editForm
func (_m *INewsService) EditNews(newsId int64, editForm models.NewsEditForm) error {
	ret := _m.Called(newsId, editForm)

	if len(ret) == 0 {
		panic("no return value specified for EditNews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, models.NewsEditForm) error); ok {
		r0 = rf(newsId, editForm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// INewsService_EditNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditNews'
type INewsService_EditNews_Call struct {
	*mock.Call
}

// EditNews is a helper method to define mock.On call
//   - newsId int64
//   - editForm models.NewsEditForm
func (_e *INewsService_Expecter) EditNews(newsId interface{}, editForm interface{}) *INewsService_EditNews_Call {
	return &INewsService_EditNews_Call{Call: _e.mock.On("EditNews", newsId, editForm)}
}

func (_c *INewsService_EditNews_Call) Run(run func(newsId int64, editForm models.NewsEditForm)) *INewsService_EditNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(models.NewsEditForm))
	})
	return _c
}

func (_c *INewsService_EditNews_Call) Return(_a0 error) *INewsService_EditNews_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *INewsService_EditNews_Call) RunAndReturn(run func(int64, models.NewsEditForm) error) *INewsService_EditNews_Call {
	_c.Call.Return(run)
	return _c
}

// ListNews provides a mock function with given fields: limit, offset
func (_m *INewsService) ListNews(limit int64, offset int64) ([]models.NewsWithCategories, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListNews")
	}

	var r0 []models.NewsWithCategories
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64) ([]models.NewsWithCategories, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) []models.NewsWithCategories); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.NewsWithCategories)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// INewsService_ListNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNews'
type INewsService_ListNews_Call struct {
	*mock.Call
}

// ListNews is a helper method to define mock.On call
//   - limit int64
//   - offset int64
func (_e *INewsService_Expecter) ListNews(limit interface{}, offset interface{}) *INewsService_ListNews_Call {
	return &INewsService_ListNews_Call{Call: _e.mock.On("ListNews", limit, offset)}
}

func (_c *INewsService_ListNews_Call) Run(run func(limit int64, offset int64)) *INewsService_ListNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *INewsService_ListNews_Call) Return(_a0 []models.NewsWithCategories, _a1 error) *INewsService_ListNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *INewsService_ListNews_Call) RunAndReturn(run func(int64, int64) ([]models.NewsWithCategories, error)) *INewsService_ListNews_Call {
	_c.Call.Return(run)
	return _c
}

// NewINewsService creates a new instance of INewsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINewsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *INewsService {
	mock := &INewsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
